version: "3.8"

services:
  postgres:
    container_name: "postgres"
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  simple-todo-api:
    container_name: 'simple-todo-api'
    restart: always
    image: simple-todo-api
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres

  simple-todo-client:
    container_name: 'simple-todo-client'
    image: simple-todo-client
    build:
      context: client/
      dockerfile: Dockerfile
      target: deploy-node
    ports:
      - 8080:8080
    depends_on:
      - simple-todo-api
      - postgres
    environment:
      - NODE_ENV=production
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - ORIGIN=http://localhost:8080
      - PORT=8080
      - VITE_SIMPLE_TODO_API="http://simple-todo-api:3000/api"
