version: "3.8"

services:
  api:
    container_name: 'simple-todo-api'
    restart: always
    image: simple-todo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres

  postgres:
    container_name: "postgres"
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
