on:
  push:
    branches:
      - main
  pull_request:
name: Linter
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          golangci_lint_flags: "--tests=false"
